### ISSUE TITLE
Better test with good alternatives: lvh.me, xip.io

### ISSUE THREAD

**Issue by eces** [bmullan91/express-subdomain#10]
Hi, Brian

I've read sources and test files, and found something left unclear with `/etc/hosts`.
It would be more nicer with `lvh.me` or `xip.io` you probably already know. That tricky domains actually can be resolved into localhost.

Thanks

**Comment by bmullan91** [comment]
@eces The tests update /etc/hosts via the pre and post scripts within `/test`. This allows the tests, and the module to be completely self contained. I don't want the tests relying on an external service for something so little, but thanks!
