### ISSUE TITLE
How to use no subdomain

### ISSUE THREAD

**Issue by FlorianBELLAZOUZ** [bmullan91/express-subdomain#11]
A code exemple is better than many words :

I need to do this :

```js
http.use(subdomain('admin',admin.router));
http.use(subdomain('www',default.router));
http.use(subdomain('',default.router));
```

And when i do :
www.myurl.com
myurl.com

i need the same result.

That is possible to add this feacture  ?

**Comment by iamchristopher** [comment]
I'm not sure if this feature is required. I think it would be better (in general and for SEO) if you simply redirected users to either http://www.myurl.com _or_ http://myurl.com instead of supporting both.

This is fairly simple to do with Express:
```
var server = require('http').createServer(app);

// This listener will intercept all requests made to the server and
// redirect them to their www equivalent
server.addListener('request', function (req, res) {
    return res.redirect('http://www.' + req.headers.host + req.url);
});
```

**Comment by bmullan91** [comment]
Yea what @iamchristopher says basically - but Id add it as a piece of middleware at the top of the stack - just check express doesn't already do this for you though.

Also, I wouldn't do `http.use(subdomain('',default.router));`
