### ISSUE TITLE
Disable route path fallback across subdomains.

### ISSUE THREAD

**Issue by thefabulousdev** [bmullan91/express-subdomain#12]
e.g. 

	// on app.js
	mainRouter.get('/login',renderLogin);
    mainRouter.use(subdomain('v1',v1Index));

    //on v1/index.js
    v1Router.use(subdomain('api', api));
    v1Router.use(subdomain('oauth',oauth));

When I go to either api or oauth subdomain and to the path /login, as no path is defined there, it falls back to the main router login handler. This is undesired behavior, how could I disable this?

Cheers.

**Comment by bmullan91** [comment]
Im not sure if this is a bug, or just the way you have ordered the middleware calls. Could you write test that outlines what you're trying to do and what you expect.

**Comment by bmullan91** [comment]
Closing...

**Comment by thefabulousdev** [comment]
Sorry Brian, I had forgotten about this. It was the way I had ordered the middleware calls. 
Once again sorry and thanks!
