### ISSUE TITLE
both api.example.co.uk, api.example, api.localhost, and localhost are failing to work

### ISSUE THREAD

**Issue by AaronNGray** [bmullan91/express-subdomain#13]
The following config.json's fail

{
  "PORT": 3000,
  "urls": {
    "API_SUBDOMAIN": "api",
    "BASE"         : "example.co.uk",
    "HOSTNAME"     : "api.example.co.uk",
    "BASE_URL"     : "example.co.uk:3000",
    "API_URL"      : "api.example.co.uk:3000",
    "V1_API_URL"   : "v1.api.example.co.uk:3000",
    "V2_API_URL"   : "v2.api.example.co.uk:3000"
  }
}

{
  "PORT": 3000,
  "urls": {
    "API_SUBDOMAIN": "api",
    "BASE"         : "localhost",
    "HOSTNAME"     : "api.localhost",
    "BASE_URL"     : "localhost:3000",
    "API_URL"      : "api.localhost:3000",
    "V1_API_URL"   : "v1.api.localhost:3000",
    "V2_API_URL"   : "v2.api.localhost:3000"
  }
}

**Comment by AaronNGray** [comment]
This seems to be a bug with node.js. 'req.domains' is not present / being generated in these cases :-

  Simple tests
req.subdomains:  []
    V GET example.com:3000
req.subdomains:  [ 'api' ]
    V GET api.example.com:3000
req.subdomains:  [ 'api' ]
    V GET api.example.com:3000/users
    1) GET example.org.uk:3000
    2) GET api.example.org.uk:3000
    3) GET api.example.org.uk:3000/users
req.subdomains:  []
    V GET localhost:3000
req.subdomains:  []
    4) GET api.localhost:3000
req.subdomains:  []
    5) GET api.localhost:3000/users

**Comment by bmullan91** [comment]
Hi @AaronNGray, 

The url `api.localhost:3000` has not top level domain, therefore it wont have any subdomains. Try placing the following in `/etc/hosts`:

```
127.0.0.1       localhost.dev
127.0.0.1       api.localhost.dev
```

Now pinging http://api.localhost.dev:3000 should do the trick.

This is all described in the [readme](https://github.com/bmullan91/express-subdomain#developing-locally).
