### ISSUE TITLE
Providing static content with express-subdomains. 

### ISSUE THREAD

**Issue by rknudson** [bmullan91/express-subdomain#22]
So this tool is amazing for RESTful services but I think it would be even more powerful if I could serve static content like so

`app.use(subdomain('sub1', express.static('/someStaticDirectory1')));`
`app.use(subdomain('sub2', express.static('/someStaticDirectory2')));`
`app.use(subdomain('sub3', express.static('/someStaticDirectory3')));`

I am not sure if this is possible, but it would be nice because I could set up 2 or 3 sub domains to point to different apps on port 80 and each would point to their own index.html. That would mean I could run multiple apps on a single port without having to deal with lazy loading of javascript.

**Comment by bmullan91** [comment]
@rknudson thanks for getting in touch. This _just works_ already, see https://github.com/bmullan91/express-subdomain/pull/23/files#diff-29a3cbdec8bef6ac7a62d3a463fd4adbR36. I should add some documentation in the readme to make it more clear.

**Comment by georgeedwards** [comment]
@bmullan91 I can't find these docs - did you get a chance to do them? 

The reason I ask is because I am facing issues with the approach described in your test above. Please see [this question](http://stackoverflow.com/questions/38809158/serve-static-content-to-subdomain-with-express). I would really appreciate some support.

**Comment by bmullan91** [comment]
@georgeedwards Added an answer to your question - http://stackoverflow.com/questions/38809158/serve-static-content-to-subdomain-with-express/38828792#38828792. I _think_ it was to do with the order of your middleware calls. If this doesn't solve it, could you add more example code 👌
