### ISSUE TITLE
subdomain connection refused

### ISSUE THREAD

**Issue by shi11** [bmullan91/express-subdomain#24]
Hi Brian, 

I'm having a tough time debugging an issue. My subdomain works perfectly locally and on my staging server but on the production server I'm getting a ERR_CONNECTION_REFUSED error. Any ideas what could be causing it?

thnx in advance,

Seth

**Comment by bmullan91** [comment]
@shi11 sorry to hear you're running into problems. I doubt its `express-subdomain`'s fault if it's working on your staging env, so there isn't much I can help with.

If you do figure it out, let me know! Good luck 😄.

**Comment by shi11** [comment]
figured it out - I'm a dumbass. I had added the subdomain to my /etc/hosts file. 

I use dev.mysite.com:3000 to mimic www.mysite.com. What I had done was added the subdomain cms.mysite.com to /etc/hosts. I fixed it by making it cms.dev.mysite.com and setting a flag in my app.js.
