### ISSUE TITLE
Subdomain proxy to subroute

### ISSUE THREAD

**Issue by collinglass** [bmullan91/express-subdomain#25]
I want to have requests rerouted as follows:

```tommy.coolestblog.com``` route to ```coolestblog.com/tommy```
```diane.coolestblog.com``` route to ```coolestblog.com/diane```
```mohammed.coolestblog.com``` route to ```coolestblog.com/mohammed```

Where it's all using the same app. Is this possible with your package?

**Comment by bmullan91** [comment]
@collinglass yup.. you'd just do the redirect inside the subdomain handler. For example:

``` js
function tommyRedirect(req, res, next) {
  return res.redirect('/tommy'); //you may need the full url
}

app.use(subdomain('tommy', tommyRedirect));
```
