### ISSUE TITLE
Subdomain routing not working

### ISSUE THREAD

**Issue by a-G1992** [bmullan91/express-subdomain#28]
I followed your module and did this:
```

var subdomain = require('express-subdomain');
var express = require('express');
var app = express();

var router = express.Router();
router.get('/', function(req, res) {
    res.send('Welcome to our API!');
});

app.use(subdomain('api', router));

app.get('/', function(req, res) {
    res.send('Homepage');
});
app.listen(3000)
console.log("server @ 3000");
```

i added in hosts file

127.0.0.1 	localhost.dev
127.0.0.1	        api.dev
127.0.0.1 	api.localhost.dev
127.0.0.1         api.localhost

I wonder why api.localhost:3000 redirects me to homepage instead of "Welcome to api".
Sorry if asking a very dumb question but need to learn this and could not find any better example.

**Comment by bmullan91** [comment]
There is no TLD with `api.localhost:3000` - use `api.localhost.dev:3000`
