### ISSUE TITLE
[Question] Specify base domain

### ISSUE THREAD

**Issue by alexeybondarenko** [bmullan91/express-subdomain#30]
For example, an application is running on `dev.example.com` and I want to add `app.dev.example.com` subdomain. 

How can I configure `express-subdomain` to add `app` subdomain inside my app?

**Comment by shinux** [comment]
app.use(subdomain('app.dev', appRouter));

**Comment by alexeybondarenko** [comment]
@shinux thanks! I found that we can also specify `subdomain offset` in express js. 
http://expressjs.com/ru/api.html#app.set
