### ISSUE TITLE
express-subdomain having same response

### ISSUE THREAD

**Issue by pascal1990** [bmullan91/express-subdomain#40]
Hi, I trying using the express-subdomain but I get the same response on the basic url and subdomain url
there is the code 

var express = require('express');
var router = express.Router();
var app = express();
var subdomain = require('express-subdomain');

app.get('/', function(req, res) {
    res.send('Homepage');
});

router.get('/', function(req, res) {
    res.send('Welcome to our API!');
});
 
router.get('/users', function(req, res) {
    res.json([
        { name: "Brian" }
    ]);
});
app.use(subdomain('api.my-contract', router));
// app.use(subdomain('api', router)); Have the same issue even use this line
app.listen(3000);

Go to the browser api.my-contract.io and my-contract.io still response "Homepage"

![sub](https://user-images.githubusercontent.com/12487736/35947804-0105fafa-0c40-11e8-870b-c14c285c47d2.PNG)

**Comment by Erim32** [comment]
Same issue, looks not working any more 😢

**Comment by bmullan91** [comment]
`app.use(subdomain('api.my-contract', router))` must go before `app.get('/', ....)`
