### ISSUE TITLE
I want to use normal domain and subdomain together.

### ISSUE THREAD

**Issue by hashmedia1** [bmullan91/express-subdomain#43]
I want load different view on subdomain and different view on normal domain

e.g example.com and subdomain.example.com

please help.

**Comment by knoxcard** [comment]
Easy, just repeat after me...

>   app.dispensary = express.Router()
>   // app.set('subdomain offset', 0)
>   var subdomain = require('express-subdomain')
>   app.nconf.get('dispensary:subdomains').forEach(sub => {
>     app.use(subdomain(sub, app.dispensary))
>   })
>   require('fs').readdirSync('./controllers/').forEach(controller => {
>     if(controller.slice(-3) == '.js')
>       require('./controllers/' + controller)(app)
>   })
>   app.get('/BingSiteAuth.xml', (req, res) => {
>     res.status(200).sendFile(require('path').join(__dirname, 'BingSiteAuth.xml'), err => {
>     })
>   })
>   app.dispensary.get('/BingSiteAuth.xml', (req, res) => {
>     res.status(200).sendFile(require('path').join(__dirname, 'BingSiteAuth.xml'), err => {
>     })
>   })
>   app.get('*', (req, res) => {
>     app.functions.show404(req, res)
>   })
>   app.dispensary.get('*', (req, res) => {
>     app.functions.show404(req, res)
>   })

**Comment by knoxcard** [comment]
Close ticket?

**Comment by csulit** [comment]
Example scenario in Godaddy

main domain is **sample.com**

Add CNAME record to your Godaddy's manage DNS 

Type: CNAME
Name: api
Value: @
TTL: 1 Hour

eg. **api.sample.com**

Express code.

```
const subdomain = require('express-subdomain');
const express = require('express');
const router = express.Router();
const app = express();
const port = 3001;

app.get('/', (req, res) => res.send('Hello from the API'));

router.get('/users', (req, res) => res.send('Welcome to users API!'));

app.use(subdomain('api', router));
app.listen(port, () => console.log('Application running on port 3001.'));
```

**Comment by bmullan91** [comment]
Thanks @knoxcard & @csulit; closing now.
