### ISSUE TITLE
Create a subdomain like slack does e.g. : https://someteam.slack.com/

### ISSUE THREAD

**Issue by strangewolf** [bmullan91/express-subdomain#44]
I am trying to implement feature like slack does in react. You all know before log-in on Slack, the url looks like this `https://www.slack.com/` , but once you logged in it change to `https://www.team.slack.com/`.

So i have my react project with 2 different layouts (landing layout & client dashboard).
What i am looking for is..

Landing layout should runs on `https://www.example.com/` 
and once client logged in successfully the domain get change into `https://www.clientname.example.com/` and admin layout gets render. 

Need helps
 how to implement this `dynamic subdomain based` rendering react-components.

**Comment by knoxcard** [comment]
```
if(req.session && req.subdomains[0] == 'www') {
  res.redirect(301, 'https://someteam.yourdomain.com/')
}
```

**Comment by sameercodes** [comment]
Hi friends i got solution for dynamic domain to work locally:

Use nginx as a server!

If use using apache server, stop that and install nginx 

first add all your domains and subdomains in /etc/hosts: (without this you can't able to make work in local system)

```
127.0.0.1 github.com
127.0.0.1 sameer.github.com
```

edit your nginx.conf file: Set a nginx reverse proxy

Add your node js project port, in my project i am using 5000, so i put 5000

```
server {
        listen 80;
        server_name github.com; 
        location / {
            proxy_pass         http://localhost:5000; 
            proxy_http_version 1.1;
            proxy_set_header Host      $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
    server {
            listen 80;
            server_name *.github.com;
            location / {
                proxy_pass         http://localhost:5000; 
                proxy_http_version 1.1;
                proxy_set_header Host      $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }

```
Instead of app.use(subdomain('yourstuff', router)); // static way
Place the below code:

```
// get your dynamic subdomain
app.use(function(req, res, next) {
  if (!req.subdomains.length || req.subdomains.slice(-1)[0] === 'www') return next();
  // otherwise we have subdomain here
  var subdomain = req.subdomains.slice(-1)[0];
  // keep it
  req.subdomain = subdomain;
  next();
});
```


```
// render a page
app.get('/', function(req, res) {
  // no subdomain
  if (!req.subdomain) {
    // render landing page
    res.render('home');
  } else {
    // render subdomain specific data
    res.render('user-page');
  }
});
```

**Comment by knoxcard** [comment]
NGINX is far more superior to Apache.  NGINX is the Usain Bolt of web servers, don't even bother using Apache.  With web development, you must be lean and mean, which leads to hyper efficiency.  If using NGINX meant you could accept 10,000 connections versus 1,000 connections with the same hardware, would you do it? Of course you would.

**Comment by hansfpc** [comment]
@strangewolf  did you do it?
