### ISSUE TITLE
Not working, even example fails

### ISSUE THREAD

**Issue by DigitalKrony** [bmullan91/express-subdomain#52]
Per your example code.

``` const express = require('express');
const subdomain = require('express-subdomain');

//////////////////////////////
//    expected responses    //
//////////////////////////////
var responses = {
    main: {
      '/': 'Simple example homepage!'
    },
    api: {
      '/': 'Welcome to our simple API!',
      '/users': [{ name: "Brian" }]
    }
  };

//////////////////////////////
//         routes           //
//////////////////////////////
var router = express.Router();

//api specific routes
router.get('/', function(req, res) {
    res.send(responses.api['/']);
});

router.get('/users', function(req, res) {
    res.json(responses.api['/users']);
});
var app = express();

app.use(subdomain('api', router));

app.get('/', function (req, res) {
  res.send(responses.main['/']);
});

app.listen(3000);
```

- `http://localhost:3000/`: expected response
- `http://api.localhost:3000/`: unexpected response, same as host above
- `http://api.localhost:3000/users`: error (`Cannot GET /users`)

Using Express `^4.16.4` and Express-Subdomain `^1.0.5`
`hosts` file has been updated to include the api sub-domain.

**Comment by bmullan91** [comment]
Your url doesn’t have a TLD.

You need to add something like this in your host file: myapp.dev, then your api.myapp.dev will work.

**Comment by DigitalKrony** [comment]
Tried and received the same results. More specifically, changing it to `local.dev` forced it into an HTTPS (which the server isn't configured for).
