### ISSUE TITLE
subdomain route not working on heroku

### ISSUE THREAD

**Issue by iamnasirudeen** [bmullan91/express-subdomain#54]
Hello i tried building a subdomain route API and i followed your documentation  but its not working, my app is running on heroku 
nodedomain.herokuapp.com and here is my code

```
const express = require('express');
const subdomain = require('express-subdomain')
const app = express();


const index = require('./index');

app.get('/', (req, res) => {
	res.send('Hello world')
})

app.use(subdomain('api.nodedomain', index));

app.listen(process.env.PORT || 2000)
```

**Comment by styfrombrest** [comment]
It doesn't work because of missing this fix: https://github.com/bmullan91/express-subdomain/pull/41/commits/103ae0795542bd752e9560f39bfd2f76fb59d719
