### ISSUE TITLE
Angular with gulp?

### ISSUE THREAD

**Issue by npearson72** [bmullan91/express-subdomain#8]
I don't know enough about node, and am using a Yeoman generator to spin up an angular app:

https://github.com/Swiip/generator-gulp-angular

I'm using it to talk to an api, but I would like to listen on wildcard subdomains.

Can you help?

**Comment by bmullan91** [comment]
This module would run on the server, running the node + express.js stack. It knows nothing about angular, and neither do I tbh.

Take it up with https://github.com/Swiip/generator-gulp-angular directly.
