### ISSUE TITLE
Routing not working

### ISSUE THREAD

**Issue by asimpletune** [bmullan91/express-subdomain#9]
Hi, I've followed your example from the [npm page](https://www.npmjs.com/package/express-subdomain) and it's just not working for me.

Here's my server
```javascript
var subdomain = require('express-subdomain');
var express = require('express');
var app = express();

// *** Code examples below go here! ***

// example.com
app.get('/', function(req, res) {
    res.send('Homepage');
});

var router = express.Router();

//api specific routes
router.get('/', function(req, res) {
    res.send('Welcome to our API!');
});

app.use(subdomain('api', router));

app.listen(3000)
```

and my /etc/hosts entries
```bash
127.0.0.1       localhost
127.0.0.1       example.com
127.0.0.1       api.example.com
```

And I still get 'Homepage', regardless of whether I go to api.example.com:3000 or example.com:3000.

**Comment by bmullan91** [comment]
Your code from var router, to app.use must go where the // *** code examples below go here! ***.

**Comment by tscritch** [comment]
Could you expand on this a little more. I'm having the same issue and am pretty confused on this. Thanks.

**Comment by bmullan91** [comment]
@tscritch check out the tests for a full example - https://github.com/bmullan91/express-subdomain/blob/master/test/simple.js
